### ISSUE TITLE
link polls with owncloud calendar

### ISSUE THREAD

**Issue by brenzi** [raduvatav/polls#58]
It would be very nice to link polls and calendar.

The poll admin should see his own calendar alongside the dates and times to be chosen for the poll.
The voter should see his own calendar alongside the poll options

Both should have the option to add blocker events in their calendar for selected options

**Comment by raduvatav** [comment]
Thanks for the suggestion @brenzi, it would indeed be nice, but I'm sorry, won't happen. See #14 for a few calendar related remarks.

tldr; It's way too complicated, the OC-calendar app doesn't help at all so what you're asking is implementing the whole functionality in polls which would ~double the code.
