### ISSUE TITLE
poll not created on last page

### ISSUE THREAD

**Issue by v1r0x** [raduvatav/polls#59]
In the current implementation the polls will be created (created flag true) after the creator clicks the finish button on the last page. I think this is confusing, because the creator (and other if the link has been shared) can vote.
The poll should be created after the creator finished the date selection or if the user clicks on another link or closes the tab there should be a warning. Something like "Do you really want to leave this page? Your poll hasn't been created yet."

**Comment by raduvatav** [comment]
@v1r0x this was kind of easy, I just moved the code.

Please see if it works and tell me to finally make a release. I don't have time anymore in the forseeable future and want to at least leave a 1.0.

**Comment by v1r0x** [comment]
I know that it wasn't hard to implement, but I wanted to share this with you

**Comment by raduvatav** [comment]
@v1r0x I didn't write "hard/easy" as "you should have done it yourself", but as "help, I want to make a release now, if possible, because I won't have any time later".

So do you know of any bugs or can I just put a "1.0" label on it now and be done with it?

**Comment by v1r0x** [comment]
Ok, sorry ;)

I think you could release it.
