### ISSUE TITLE
Set correct versions on apps.owncloud.com and info.xml/version

### ISSUE THREAD

**Issue by RealRancor** [raduvatav/polls#62]
Hi,

after tagging the stable release 1.0 (which runs fine here) it could be useful to also use this version number at:

https://apps.owncloud.com/content/show.php/Polls?content=167919

and:

https://github.com/raduvatav/polls/blob/v1.0/appinfo/info.xml
https://github.com/raduvatav/polls/blob/v1.0/appinfo/version

to avoid confusions about the current used different versions 0.3, 0.6.2 and 1.0.

When changing the version in info.xml and version a re-tagging of v1.0 is probably needed.

**Comment by raduvatav** [comment]
Actually it's just 0.6.2 (in the source) and 1.0 (tag). 0.3 on the apps.oc page is just changelog. Yes, I should change that too... If I change the version in the source it will trigger a DB update for nothing... I don't know, I'll think of something. And rewrite the text on the apps.oc page. When I'll have more time and I won't be this tired :)

**Comment by RealRancor** [comment]
Hi,

absolutely fine with the current changes.
