### ISSUE TITLE
Make new release 0.6.3

### ISSUE THREAD

**Issue by RealRancor** [raduvatav/polls#67]
Hi,

with the latest translation fixes in #66 it could be useful to make a new release 0.6.3 on the appstore. By following this steps:

https://github.com/owncloud/core/issues/18116#issuecomment-129445478

the update could be directly installed from within oC.

**Comment by raduvatav** [comment]
@RealRancor I updated to 0.6.3 (source, dwl. link on apps.owncloud). Can you please do the rest? (I didn't quite understand and don't have the time to look into). I made you "contributor" here, don't know if that helps somehow with rights or something...

**Comment by RealRancor** [comment]
@raduvatav Nearly done. Uploading the polls.zip containing a folder "polls" instead of "polls-0.6.3" to https://github.com/raduvatav/polls/releases was missing. Now the appstore download url needs to point to: https://github.com/raduvatav/polls/releases/download/0.6.3/polls.zip instead of https://github.com/raduvatav/polls/archive/0.6.3.zip and this should be fine.

**Comment by RealRancor** [comment]
@raduvatav Any changes that you could update the app on the appstore as described:

> Now the appstore download url needs to point to: https://github.com/raduvatav/polls/releases/download/0.6.3/polls.zip instead of https://github.com/raduvatav/polls/archive/0.6.3.zip and the link to master could be removed.
>
>Additionally the version on the appstore can be changed to 0.6.3 and this should be fine.

Thanks

**Comment by raduvatav** [comment]
@RealRancor done; sorry for the delay

**Comment by RealRancor** [comment]
> done; sorry for the delay

Thanks. But you definitely don't need to say sorry. :-)
