### ISSUE TITLE
Error when trying to enable

### ISSUE THREAD

**Issue by farson2003** [raduvatav/polls#68]
When trying to enable via Owncloud admin backend, I get the error "App can't be installed because the version in info.xml/version is not the same as the version reported from the app store".

Using OC 8.1.1.

**Comment by RealRancor** [comment]
That should be fixed if the newer version is correctly released at the appstore: https://github.com/raduvatav/polls/issues/67#issuecomment-133044089

**Comment by RealRancor** [comment]
@farson2003 Please try again. Works here now with oC 8.1
