### ISSUE TITLE
Errors on public votings

### ISSUE THREAD

**Issue by darootler** [raduvatav/polls#70]
Hi,

if anyone votes on a public enabled poll i am getting a http 500 error Code and the following errors:

{PHP} Undefined variable: title at /var/www/owncloud/apps/polls/templates/finish.php#70

and

[Wed Sep 16 20:32:20.288463 2015] [:error] [pid 15927] [client X.X.X.X:49924] PHP Fatal error:  Class 'OC_Mail' not found in /var/www/owncloud/apps/polls/templates/finish.php on line 80, referer: https://my.host.com/owncloud/index.php/apps/polls/goto/j5wh8jisp7b999p2

If anyone needs more details please let me know

Best regards

Richard

**Comment by RealRancor** [comment]
Hi,

please try https://github.com/raduvatav/polls/pull/71

**Comment by darootler** [comment]
Hi,

problems seem to be fixed with the new finish.php

Best regards

**Comment by RealRancor** [comment]
Hi,

and thanks for the feedback. You can also directly test the current master which just got some smaller fixes:

https://github.com/raduvatav/polls/compare/0.6.3...master

from https://github.com/raduvatav/polls/archive/master.zip (extract into /apps/polls overwriting existing files).

Feedback welcome, then it could be possible to release a new version at the appstore containing all the fixes.

**Comment by darootler** [comment]
Hi,

i just downloaded the current master. If i encounter any problems i'll let you know :-)

Best regards
