### ISSUE TITLE
Replace OC_L10N::forceLanguage with public method

### ISSUE THREAD

**Issue by RealRancor** [raduvatav/polls#77]
./occ app:check-code polls has currently 2 errors left:

```
Analysing /var/www/owncloud/apps/polls/templates/finish.php
 2 errors
    line   73: OC_L10N - static method call on private class
    line   94: OC_L10N - static method call on private class
App is not compliant
```

but i have no idea how to fix those three lines:

https://github.com/raduvatav/polls/blob/master/templates/finish.php#L4
https://github.com/raduvatav/polls/blob/master/templates/finish.php#L73
https://github.com/raduvatav/polls/blob/master/templates/finish.php#L94

to make it compliant. Anyone any ideas?

**Comment by RealRancor** [comment]
I think if that one is fixed we could release 0.6.4

**Comment by mckaygerhard** [comment]
this only happened if u do not support oc 6 and oc7, this only happened for oc 8.1+ due new api deprecated many methods and make strong the usage of the api, private methods in api are suject to change without any advertising that why now for oc 8.1+ are market as error..

**Comment by RealRancor** [comment]
> this only happened if u do not support oc 6 and oc7, this only happened for oc 8.1+ due new api deprecated many methods and make strong the usage of the api, private methods in api are suject to change without any advertising that why now for oc 8.1+ are market as error..

Exactly why i had created this issue here.

> i think u must support oc 7 due still are supported by oc payd version, oc 8.X has still some erros with development due not concensus in api usage

No one needs to support older versions of oC. A app developer is free to support just the latest version of oC. :-)

**Comment by mckaygerhard** [comment]
i'll will fix that problem but only for oc7 or 6 due i do not have php 5.4 and do not have "lasted" or "a-la-moda" just only "working and faster" such php 5.3.32 

i currently studing the deprecated api and newer funtions/methods, i'll made some pulls when i have enought knowledg to, please waith a little (i see many developers stop made apps to oc due that so frecuently changes between oc api and versions)

**Comment by RealRancor** [comment]
To make Polls compatible with 8.2 this needs to be either replaced or removed: https://github.com/raduvatav/polls/issues/88

**Comment by RealRancor** [comment]
Seems that method was completely removed within core: https://github.com/owncloud/core/commit/6b53f7c40e8bbaecfa20a3b19b3164e332903f59 . Have removed that call from the app completely so closing this for now.
