### ISSUE TITLE
App store version mismatch error

### ISSUE THREAD

**Issue by pjz** [raduvatav/polls#81]
Running 8.1.3 with the 'allow experimental apps' flag, I can see the Polls app, but trying to enable it gets me: 
```
App can't be installed because the version in info.xml/version is not the same as the version reported from the app store
```

**Comment by RealRancor** [comment]
Seems the appstore is not sending a version at all. Do you also get "Polls" showing in the "Tools" category but without a version?

**Comment by raduvatav** [comment]
forgot to set version in app-store; fixed now

**Comment by RealRancor** [comment]
Thanks. Update from 0.6.3 to 0.6.4 just worked fine.
