### ISSUE TITLE
error in access_dialog.php

### ISSUE THREAD

**Issue by darootler** [raduvatav/polls#82]
Hi,

i am using the current master and getting the following error a few times. The problem is that i cannot reproduce the error, it's popping up if i use the polls app:

{PHP} Invalid argument supplied for foreach() at /var/www/owncloud/apps/polls/templates/access_dialog.php#44

If more information is needed please let me know.

Best regards

Richard

**Comment by RealRancor** [comment]
Hi,

thanks for reporting this. Had used the wrong method while doing #73. Should be fixed with https://github.com/raduvatav/polls/commit/39606eba54584fa58f6a0a01f9c763cfe7f9ba6d

**Comment by RealRancor** [comment]
Just have re-released polls 0.6.4 with this minor fix. You can disable and remove the app from the "not enabled" category and afterwards enable it again from the "Tools" category.

**Comment by darootler** [comment]
Thank you!

Best regards

Richard

Am 02.10.2015 um 18:09 schrieb RealRancor <notifications@github.com <mailto:notifications@github.com> >:

Just have re-released polls 0.6.4 with this minor fix. You can disable and remove the app from the "not enabled" category and afterwards enable it again from the "Tools" category.
