### ISSUE TITLE
After Vote Blank Screen

### ISSUE THREAD

**Issue by loorean** [raduvatav/polls#84]
Iam using OC 8.1.3, after installing polls i tested it and one poll worked fine for me.

If i create a new poll or someone wants to vote one my first poll after choosing name and date and comment and click submit a white screen occurs.

Update:  Logged in members can vote but for the others it isnt possible

Errorlog:
Error	PHP	Class 'User' not found at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/finish.php#9	2015-10-03T10:16:30+00:00
Error	PHP	The use statement with non-compound name 'OC_L10N' has no effect at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/finish.php#4	2015-10-03T10:16:30+00:00
Error	PHP	Class 'User' not found at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/finish.php#9	2015-10-03T10:16:25+00:00
Error	PHP	The use statement with non-compound name 'OC_L10N' has no effect at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/finish.php#4	2015-10-03T10:16:25+00:00

**Comment by loorean** [comment]
Testpoll: http://daten.lz22.com/index.php/apps/polls/goto/odpuvfnbfnunha58

**Comment by RealRancor** [comment]
Hi,

can you check the content of the templats/finish.php against:

https://github.com/raduvatav/polls/blob/v0.6.4/templates/finish.php

This one has an empty line 9 where your version is telling that an class not existing there is found:

https://github.com/raduvatav/polls/blob/v0.6.4/templates/finish.php#L9

**Comment by loorean** [comment]
Line 9 is empty in my version

**Comment by RealRancor** [comment]
No idea then, sorry. The OC_L10N message itself shouldn't be responsible for this and is fixed if some one is helping with https://github.com/raduvatav/polls/issues/77

**Comment by loorean** [comment]
That Blank screen only occurs if a unregistred will vote and clicks submit....

**Comment by loorean** [comment]
Got another logentry: ( i have disabled a statistictool) 

Class 'User' not found at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/finish.php#7 	2015-10-03T11:24:03+00:00
Error 	PHP 	The use statement with non-compound name 'OC_L10N' has no effect at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/finish.php#4 	2015-10-03T11:24:03+00:00
Error 	PHP 	max(): Array must contain at least one element at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/last.php#276 	2015-10-03T11:23:53+00:00
Error	PHP	max(): Array must contain at least one element at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/last.php#276	2015-10-03T11:23:53+00:00
Error	PHP	max(): Array must contain at least one element at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/last.php#276	2015-10-03T11:23:35+00:00

**Comment by RealRancor** [comment]
Hi,

could you provide the steps to reproduce this?

What i did was to create a public vote, choose three days with one single hour. Then voted from within another browser as a public user without an oC account and the voting worked just fine.

**Comment by loorean** [comment]
I did it like u and after choosing a day and make a comment after pressing the send button die url changes to http://daten.lz22.com/index.php/apps/polls/ and got an http 500 error / white screen....

**Comment by RealRancor** [comment]
Hi,

just tested few seconds ago with the "test" user and worked just fine here.

**Comment by loorean** [comment]
Update: after deleting "use \OC_L10N" in finish php it works.

Do u have an idea on what it depends ? Language DE?

**Comment by RealRancor** [comment]
Honestly i have no idea but as the two methods ```OC_L10N::forceLanguage`` are using the prefix it should be fine to remove this.

**Comment by loorean** [comment]
Yes but now i get those errors but it still works :+1: 
Error 	PHP 	max(): Array must contain at least one element at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/last.php#276 	2015-10-03T15:58:46+00:00
Error 	PHP 	Invalid argument supplied for foreach() at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/last.php#59 	2015-10-03T15:58:46+00:00
Error 	PHP 	array_keys() expects parameter 1 to be array, null given at /is/htdocs/wp10582120_E8LHCUGARA/www/lz22_clowd/apps/polls/templates/last.php#59

**Comment by RealRancor** [comment]
Could you create a new issue providing the steps (like chosen access, type, expiring, ...) how to re-produce this?
