### ISSUE TITLE
Problem on finishing a poll

### ISSUE THREAD

**Issue by darootler** [raduvatav/polls#88]
Hi,

i got the following error on finishing a poll:

PHP Fatal error:  Call to undefined method OC_L10N::forceLanguage() in /var/www/owncloud/apps/polls/templates/finish.php on line 94

If you need more Information please let me know.

Best regards

Richard

**Comment by RealRancor** [comment]
Hi,

might be useful to give at least some info about your environment. Especially the oC version you're running. If you're on oC 8.2 -> The app isn't checked for compatibility with oC 8.2.

**Comment by darootler** [comment]
Hi,

that maybe the problem. I am using oC 8.2. Sorry, didn't remember to check for compatibility. 

Ubuntu 14.04
Apache 2.4.7
PHP 5.5.9

Best regards

Richard

Am 01.11.2015 um 14:52 schrieb RealRancor <notifications@github.com <mailto:notifications@github.com> >:

Hi,

might be useful to give at least some info about your environment. Especially the oC version you're running. If you're on oC 8.2 -> The app isn't checked for compatibility with oC 8.2.

**Comment by RealRancor** [comment]
Hi,

thanks. Replacing OC_L10N::forceLanguage() with a possible public API is tracked in https://github.com/raduvatav/polls/issues/77 so i'm closing this.
