### ISSUE TITLE
clicking on the app-button ends on a blank page

### ISSUE THREAD

**Issue by Liwindo** [raduvatav/polls#96]
### Steps to reproduce
1. Have the old polls-app installed
2. Upgrade to the new polls-app
3. activate the app
4. click on the app button

### Expected behaviour
The app works fine

### Actual behaviour
A blank page appears

### Server configuration
**Operating system**: Ubuntu 14.04.4

**Web server:** apache with nginx proxy

**Database:** mysql 5.5.47-0ubuntu0.14.04.1

**PHP version:** 7.0.3

**ownCloud version:** 8.2.2

```
### Logs
#### ownCloud log (data/owncloud.log)
```
TypeError: Argument 2 passed to OCP\AppFramework\Db\Mapper::findEntities() must be of the type array, null given, called in /var/www/vhosts/domain.tld/owncloud/apps/polls/db/eventmapper.php on line 47 at /var/www/vhosts/domain.tld/owncloud/lib/public/appframework/db/mapper.php#318 
```

**Comment by RealRancor** [comment]
@Liwindo Try the rework of the app available at https://apps.owncloud.com/content/show.php/Polls?content=174671

This one here is very unlikely receiving any bugfixes.

Btw. oC 8.2.2 is not compatible with PHP 7. You should wait until 8.2.3 is released bringing PHP 7 compatibility in oC.

**Comment by RealRancor** [comment]
Ah, nvm. You have already reported that at the new app: https://github.com/v1r0x/polls/issues/3 so just closing here.
